### ISSUE TITLE
Making the Result Text from the Identify Command Copy-able

### ISSUE THREAD

**Issue by nv1t** [ISpillMyDrink/OpenSuperClone#12]
**Is your feature request related to a problem? Please describe.**
The Result of the identify command is not in the cmd, nor copyable from the results window.

**Describe the solution you'd like**
either outputting it in the cmd as well, or provide a button or a selectable text to copy the bytes, or everything, or whatever. (nicer output)

**Comment by ISpillMyDrink** [comment]
Analysis, SMART, and Identify windows are currently being reworked, this is planned for the 2.5 release.
In the meantime, the Identify command output is also written to the logfile.

**Comment by nv1t** [comment]
That is great news. All of these were bugging me a lot.

**Comment by ISpillMyDrink** [comment]
With the 2.5.0 release out, this can be considered done now.
