### ISSUE TITLE
Allow setting partitions as sources

### ISSUE THREAD

**Issue by leandro-gracia-gil** [ISpillMyDrink/OpenSuperClone#18]
I'm trying to continue a ddrescue session I did where the source was not a device but a specific partition. While I could import my ddrescue log file without any problems, I cannot continue the session because OpenSuperClone only lets me select devices as sources, not their partitions. If I select the device where the partition is, I unsurprisingly get an error saying that the sizes do not match.

Is there any way to select a partition as source instead of a device?

**Comment by ISpillMyDrink** [comment]
You can use the "Generic Source File" mode to select a partition in /dev.

**Comment by leandro-gracia-gil** [comment]
Understood. Thanks!
