### ISSUE TITLE
Is this difference than hddsuperclone

### ISSUE THREAD

**Issue by HanalogInstruments** [ISpillMyDrink/OpenSuperClone#2]
Hi,

Is this OpenSuperClone difference than the hddsuperclone?

Best regards,

**Comment by ISpillMyDrink** [comment]
Just to not have this floating without a comment. This is a fork of the HDDSuperClone project by Scott Dwyer, all the user-facing differences are listed in the changelog, all the development facing ones in the commit log (as always...)
